import Link from "next/link";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { buildPalette, paletteAdvice } from "@/lib/wardrobe-colors";
import { createClient } from "@/lib/supabase/server";

export const metadata = { title: "Colour palette" };

export default async function PalettePage() {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getClaims();
  if (!auth?.claims) redirect("/login");
  const { data } = await supabase.from("clothing_items").select("color");
  const palette = buildPalette((data ?? []).map((item) => item.color));
  const advice = paletteAdvice(palette);

  return <main className="min-h-screen bg-[#f8f7f4] px-6 py-8 text-[#201d1a] sm:px-10"><header className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/dashboard" className="text-xl font-semibold tracking-tight">Style Set</Link><Button asChild variant="outline"><Link href="/wardrobe">Wardrobe</Link></Button></header><section className="mx-auto max-w-5xl py-14"><p className="text-sm font-medium text-[#766b61]">YOUR COLOUR PALETTE</p><h1 className="mt-3 text-5xl font-semibold tracking-[-0.04em]">See the colours you reach for.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#6f655d]">Style Set builds this palette from your wardrobe, making it easier to spot your foundations and favourite accent colours.</p>{palette.length ? <><section className="mt-10 overflow-hidden rounded-3xl border border-[#e5ddd5] bg-[#fcfbf9]"><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6">{palette.map((color) => <article key={color.name} className="border-b border-r border-[#e5ddd5] p-4 last:border-r-0 sm:last:border-r lg:border-b-0"><div className="aspect-square rounded-2xl border border-black/10" style={{ backgroundColor: color.hex }} /><p className="mt-3 font-semibold">{color.name}</p><p className="text-sm text-[#6f655d]">{color.count} {color.count === 1 ? "piece" : "pieces"}</p></article>)}</div></section><section className="mt-8 grid gap-4 sm:grid-cols-2"><article className="rounded-3xl bg-[#302a25] p-6 text-white"><p className="text-xs font-medium tracking-[0.14em] text-[#d8d0c8]">YOUR FOUNDATION</p><h2 className="mt-3 text-2xl font-semibold">Your easiest outfit base</h2><p className="mt-3 leading-7 text-[#d8d0c8]">{advice.foundation.length ? `${advice.foundation.map((color) => color.name).join(", ")} make up the core of your wardrobe. Start with one or two of these, then add a contrast.` : "Add a few neutral pieces to create effortless outfit foundations."}</p></article><article className="rounded-3xl border border-[#e5ddd5] bg-[#fcfbf9] p-6"><p className="text-xs font-medium tracking-[0.14em] text-[#766b61]">ACCENT COLOURS</p><h2 className="mt-3 text-2xl font-semibold">Make a look feel intentional</h2><p className="mt-3 leading-7 text-[#6f655d]">{advice.accents.length ? `${advice.accents.map((color) => color.name).join(", ")} are your standout shades. Pair one accent with a neutral foundation for an easy, balanced look.` : "Your current wardrobe is beautifully neutral. Add one colour you love when you want more variety."}</p></article></section></> : <section className="mt-10 rounded-3xl border border-dashed border-[#cfc5bb] p-10 text-center"><h2 className="text-2xl font-semibold">Your palette will appear here.</h2><p className="mt-3 text-[#6f655d]">Add clothing items with colour details to reveal the tones already in your wardrobe.</p><Button asChild className="mt-6 rounded-xl bg-[#302a25] text-white hover:bg-[#4a4037]"><Link href="/wardrobe">Add to wardrobe</Link></Button></section>}</section></main>;
}
